### ISSUE TITLE
Missing type property

### ISSUE THREAD

**Issue by 9o** [chentsulin/sweetalert-react#11]
I don't see the type property as used in vinilla sweetalert. Whats the status on this?

Thanks!

**Comment by chentsulin** [comment]
you can use on of `'warning', 'error', 'success', 'info', 'input'` as props:
https://github.com/chentsulin/sweetalert-react/blob/master/src/SweetAlert.js#L74

Just like:
```js
<SweetAlert
        show={this.state.show}
        title="Demo"
        type="success"
        text="SweetAlert in React"
        onConfirm={() => this.setState({ show: false })}
/>
```

**Comment by chentsulin** [comment]
`type` prop added to complex example, please check it out:
https://github.com/chentsulin/sweetalert-react/blob/master/examples/complex/components/App.js#L21
