### ISSUE TITLE
Support Server Rendering

### ISSUE THREAD

**Issue by chentsulin** [chentsulin/sweetalert-react#15]

**Comment by alex-shamshurin** [comment]
This does not work at all even while importing

this line produces error `window is not defined`
`import SweetAlert from 'sweetalert-react';`

because of this

```
var logStr = function logStr(string) {
	  if (window.console) {
	    // IE...
	    window.console.log('SweetAlert: ' + string);
	  }
	};
```

**Comment by chentsulin** [comment]
One of solution is wrap it in a if condition check:

```js
if (window) {
  const SweetAlert = require('sweetalert-react').default;
}
```

**Comment by alex-shamshurin** [comment]
O course I did it in componentDidMount. But this issue should be fixed

**Comment by eXon** [comment]
It would be nice to have a no op with a simple check if the DOM is there. It's silly to wrap it under a component just for that reason.

**Comment by chentsulin** [comment]
https://github.com/chentsulin/sweetalert-react/releases/tag/v0.4.6
