### ISSUE TITLE
Sweetalert displays 'Not valid!'

### ISSUE THREAD

**Issue by bzeiler** [chentsulin/sweetalert-react#18]
```
<SweetAlert
  show={this.state.show}
  title="Demo"
  text="SweetAlert in React"
  onConfirm={() => this.setState({ show: false })}
/>
```

Displays

![image](https://cloud.githubusercontent.com/assets/2480963/13668834/32457998-e6b7-11e5-8aa3-40b8f60df724.png)

Tried and tested with all the different examples found in /examples.
Same result across the board.

Doing `npm install sweetalert-react`

**Comment by adamtay82** [comment]
I have the same problem - how did you fix it?

**Comment by franvera** [comment]
The css file is missing, importing it should fix the issue @adamtay82

**Comment by alvaro-paco** [comment]
@adamtay82 just include this SCSS file [sweetalert.scss](https://github.com/t4t5/sweetalert/blob/master/dev/sweetalert.scss) in your code.
