### ISSUE TITLE
simply things be made complicated

### ISSUE THREAD

**Issue by yi** [chentsulin/sweetalert-react#20]
```
Removed Options

timer: You should use setTimeout and pass show as false.
closeOnConfirm: You should pass show as false via onConfirm.
closeOnCancel: You should pass show as false via onCancel.
allowEscapeKey: You should pass show as false via onEscapeKey.
allowOutsideClick: You should pass show as false via onOutsideClick.
```

not a good idea, an extra stateful node must be create for using this sweetalert thing.

**Comment by chentsulin** [comment]
A good React Component should follow this model: `(state, props) => HTML`. However, those five methods have explicit side effects, so I thought the design like this is the best option that we can take for now, or you will lost the single source of truth about your sweetalert element's state.

If you don't want to keep a state for sweetalet, you should use `sweetalert` package directly.
