### ISSUE TITLE
Why did I can't put cancel and confirm buttons in one line.

### ISSUE THREAD

**Issue by Caballarii** [chentsulin/sweetalert-react#21]
I did't import css/less. Should I just import it in jsx instead of in html?

**Comment by chentsulin** [comment]
You should import `sweetalert.css` from cdn, file, node_modules(sweetalert/dist/sweetalert.css) or wherever can find the css code.

Checkout full examples [here](https://github.com/chentsulin/sweetalert-react/tree/master/examples).
