### ISSUE TITLE
Alert doesn't close when 'go back' or 'go forward' in browser

### ISSUE THREAD

**Issue by kopaygorodsky** [chentsulin/sweetalert-react#51]
If user won't confirm or cancel alert and he just press 'go back' in a browser - Alert is still mounted.

**Comment by chentsulin** [comment]
This is how React works. You can listen history change and set `show: false` when it mounted.

**Comment by chentsulin** [comment]
Added a new `history-change` example: https://github.com/chentsulin/sweetalert-react/blob/master/examples/history-change/components/App.js
