### ISSUE TITLE
Component as popup body

### ISSUE THREAD

**Issue by ArkadyB** [chentsulin/sweetalert-react#53]
Hi, 

Is it possible to render another component as html body? How?

**Comment by ArkadyB** [comment]
Done. Using ReactDOMServer.renderToStaticMarkup.

**Comment by khoaanh2212** [comment]
renderToStaticMarkup just render static html,if your component has complicate handler, none of them can work.
example you have an component with some onClick function,when you use renderToStaticMarkup,it doesn't work.

**Comment by vjustov** [comment]
@khoaanh2212 did you ever came across a way to keep render a Component and keep the handlers working with react-sweetalert?

**Comment by khoaanh2212** [comment]
@vjustov i need to put an props.children into sweetalert,and the only way until now is build a new Components SweetAlert.this project didn't render anything,just use sweetalert.js to run popup.
