### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by neighborhood999** [chentsulin/sweetalert-react#9]
Excuse me, I have something problem:  

I clone this repo and running `npm install`, 
and switch to `example/simple` this example, and I running `npm install`.

after running  `npm install`, I execute `npm start`, have something error:
`Module not found: Error Cannot resolve module 'react'`
![](http://i.imgur.com/NZCqmkv.png)  

then, I open `package.json` add `react` into `dependencies`, 
save and run `npm start` it can work.

Why have this error message? :anguished:  
Thank you.

**Comment by chentsulin** [comment]
You should  run `npm run build` first if you clone from github.

https://github.com/chentsulin/sweetalert-react/blob/master/package.json#L15

Line 15: use `babel` to compile es6, jsx syntax
Line 16: use `webpack` to build umd module (which can run in global, amd, commonjs environments)
Line 17: use `webpack` to build minified umd module
Line 18: do 15, 16, and 17

**Comment by chentsulin** [comment]
Maybe I should add a npm script like this:

```
"postinstall": "node -e \"require('fs').stat('lib', function (e, s) { process.exit(e || !s.isDirectory() ? 1 : 0) })\" || npm run build",
```

And then it will build after npm install
