### ISSUE TITLE
Suggestion: Using active fork of sweetalert

### ISSUE THREAD

**Issue by VasilyShelkov** [chentsulin/sweetalert-react#93]
Just noticed that sweetalert is not maintained anymore: https://github.com/limonte/sweetalert2. Don't know if it's worth doing, nor a priority just thought I'd point out the original sweetalert hasn't merged a PR since 2014.

**Comment by alex-shamshurin** [comment]
I think both are maintained https://github.com/t4t5/sweetalert and  https://github.com/limonte/sweetalert2

**Comment by chentsulin** [comment]
I'd like to keep using `/t4t5/sweetalert` and upgrade to v2.

**Comment by alex-shamshurin** [comment]
Hmm, if I have time I will make a fork. But now I did this for sweetalert2 https://github.com/alex-shamshurin/sweetalert2-react
