### ISSUE TITLE
Render custom coponent that operates with state

### ISSUE THREAD

**Issue by CandyOgre** [chentsulin/sweetalert-react#97]
SweetAlert code: 
```
<SweetAlert
      show={cartOpened}
      title="Cart"
      html
      text={renderToStaticMarkup(<Cart />)}
      onConfirm={showCart(false)}
    />
```

Cart is a complex component, that uses `redux`. I\`m using `recompose` too. 

Got a following error:
`Uncaught Error: Could not find "store" in either the context or props of "Connect(withState(withHandlers(Cart)))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(withState(withHandlers(Cart)))".`

What can I do?

**Comment by HenryHug** [comment]
Did you get any solution for this problem? Please help me out. I am stucking in this problem
